
</body>


<!--css-->
<footer class="footer">
<div class = "container">
    <div class="paragraphContainer" style="
    margin-left: auto;
    margin-right: auto;
">
    <p style="
    text-align: center;
">Copyright Afzal Muhammad (Univeristy of Salford) 2018</p>
    </div>
</div>
</footer>
<script src="https://code.jquery.com/jquery.js"></script>
 <!--Some Bootstraps links-->
 <link href="css/bootstrap.css" rel="stylesheet">

<script src="css/js/bootstrap.js"></script>

<script src="css/js/bootstrap.min.js"></script>

<script src="css/jquery-3.3.1.js"></script> 
</html>