<!DOCTYPE html5>
<html lang="en">

<head>
    <meta charset="<?php echo $view->pageTitle; ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!--Some Bootstraps links-->
    <link href="css/bootstrap.css" rel="stylesheet">

    <script src="css/js/bootstrap.js"></script>

    <script src="css/js/bootstrap.min.js"></script>

    <script src="https://code.jquery.com/jquery.js"></script>

    <!--CSS-->

    <link href="css/my-style.css" rel="stylesheet">

    <!-- Fonts/icons -->

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
        crossorigin="anonymous">

    <title>HOME
        <?php echo $view->pageTitle; ?>
    </title>
</head>


<body>

    <!--Navigation bar-->

    <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="index.php">
                <img src="Images/logo.png"></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="index.php">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="campsiteList.php?page=1">Search Campsite</a>
                    </li>
                    <?php 
                if (!$userData->isUserLogged()) { echo '
                <li class="nav-item">
                    <a href="Login.php">Login</a>
                </li>   
                <li class="nav-item">
                    <a href="registerform.php">Sign up</a>
                </li>
                

                </ul> ';
                }
                else {
                    echo '
                <li class="nav-item">
                    <a href="logout.php">Logout</a>
                </li> 
                <li class="nav-item">
                <a href="favourite.php">Favourites</a>
            </li>
            <li class="nav-item">
                <a href="addCampsite.php">Add Your Campsite</a>
            </li> 
            <li>
                    <a href="campsiteAdmin.php" >Admin Panel</a>
                </li>
            <li class="nav-item">
            <a href="userProfile.php">My Profile</a>
        </li>   
                </ul> 
                <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Admin Feature
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="campsiteAdmin.php?campsitePage=campsitePage">Campsite</a>
            <a class="dropdown-item" href="campsiteAdmin.php?userPage=userPage">User</a>
        </div>
        </div>';
                }
                ?>
            </div>
        </div>
    </nav>