<?php require_once('Template/header.phtml') ?>
<body>
<div class="container" id="container-campsitePage">
<h2 class="title-campsitePage"><?php echo $campsite->getCampsiteName(); ?></h2>    
    <div class="row">
        <div class="col-sm-8 col-md-6  col-lg-4">
            <div><img src="Images/<?php if($campsite->getPhoto() != null) {echo $campsite->getPhoto();} else { echo 'Default.jpg';}?>"></div>
            <div><?php echo $campsite->getCampsiteStreetAddress();?> </div>
            <div><?php echo $campsite->getPostcode();?> </div>
            <div><?php echo $campsite->getCity();?> </div>
            <div><?php echo $campsite->getCountry();?> </div>

        </div>
        <div class="col-sm-8 col-md-6 col-lg-4 " id="campsite-table">
                <div>
                    <table class="table table-hover">
                        <tr>
                            <th scope="col" colspan="2">Facility</th>
                            <th scope="col">Avaliability</th>
                        </tr>
                        <tr>
                            <td><i class="fas fa-shower"></i></td>  
                            <td>shower</td>
                            <td><?php if($campsite->get_cafe()){echo 'yes';}else{echo 'no';}?></td>
                        </tr>
                        <tr>
                            <td><i class="fas fa-wifi"></i></td>
                            <td>wifi</td>
                            <td><?php if($campsite->get_wifi()){echo 'yes';}else{echo 'no';}?></td>
                        </tr>
                        <tr>
                            <td><i class="fas fa-coffee"></i></td>
                            <td>Coffee</td>
                            <td><?php if($campsite->get_cafe()){echo 'yes';}else{echo 'no';}?></td>
                        </tr>
                        <tr>
                            <td><i class="fab fa-accessible-icon"></i></td>
                            <td>Accessibility</td>
                            <td><?php if($campsite->get_disabled()){echo 'yes';}else{echo 'no';}?></td>
                        </tr>
                        <tr>
                            <td>  <i class="fas fa-tint"></i></td>
                            <td>Water</td>
                            <td><?php if($campsite->get_water()
                              ){echo 'yes';}else{echo 'no';}?></td>
                        </tr>
                        <tr>
                            <td><i class="far fa-smile"></i></td>
                            <td>Family</td>
                            <td><?php if($campsite->get_family()){echo 'yes';}else{echo 'no';}?></td>
                        </tr>
                    </table>
                </div>
            </div>
    <div class="col-sm-8 col-md-6 col-lg-4 " id="campsite-rating">
    <h4>Leave a rating</h4>
    <?php if($userData->isUserLogged()):?>    
    <form action="<?php $_SERVER['PHP_SELF']; ?>" method="post">
    <div class="row">
                                          <span class="rating">
                                                 <input type="radio" class="rating-input" id="rating-input-1-5-5" name="rating-input-5" value="rating-input-1-5-5">
                                                 <label for="rating-input-1-5-5" class="rating-star"></label>
                                                 <input type="radio" class="rating-input" id="rating-input-1-4-5" name="rating-input-5" value="rating-input-1-4-5">
                                                 <label for="rating-input-1-4-5" class="rating-star"></label>
                                                 <input type="radio" class="rating-input" id="rating-input-1-3-5" name="rating-input-5" value="rating-input-1-3-5">
                                                 <label for="rating-input-1-3-5" class="rating-star"></label>
                                                 <input type="radio" class="rating-input" id="rating-input-1-2-5" name="rating-input-5" value="rating-input-1-2-5">
                                                 <label for="rating-input-1-2-5" class="rating-star"></label>
                                                 <input type="radio" class="rating-input" id="rating-input-1-1-5" name="rating-input-5" value="rating-input-1-1-5">
                                                 <label for="rating-input-1-1-5" class="rating-star"></label>
                                                 <input type="hidden" name="campsiteID" value="<?php echo $campsite->getCampsiteID();?>">
                                          </span>
                                   </div>
            <input type="submit" name="submit" value="Submit rating">
        </form>
        <h4>Owner details:</h4>
        <div><?php echo $campsite->get_ownerName();?></div>
        <div><?php echo $campsite->get_ownerContact();?></div>
        <?php else: ?>
        <h4>Log in first</h4>
    <?php endif ?>
    </div>
</div>
</div>

<?php require_once('Template/footer.phtml') ?>