<?php require_once('Template/header.phtml') ?>
<body>
<div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-6  col-lg-4">
                <div><img src="Images/default.jpg"></div>
            </div>
            <div class="col-sm-8 col-md-6 col-lg-4">
                    <div>
                        <table>
                            <tr>
                                <th colspan="2">Facility</th>
                                <th>Avaliability</th>
                            </tr>
                            <tr>
                                <td><i class="fas fa-shower"></i></td>  
                                <td>shower</td>
                                <td>Yes</td>
                            </tr>
                            <tr>
                                <td><i class="fas fa-wifi"></i></td>
                                <td>wifi</td>
                                <td>Yes</td>
                            </tr>
                            <tr>
                                <td><i class="fas fa-coffee"></i></td>
                                <td>Coffee</td>
                                <td>Yes</td>
                            </tr>
                            <tr>
                                <td><i class="fab fa-accessible-icon"></i></td>
                                <td>Accessible</td>
                                <td>Yes</td>
                            </tr>
                            <tr>
                                <td>  <i class="fas fa-tint"></i></td>
                                <td>Water</td>
                                <td>Yes</td>
                            </tr>
                            <tr>
                                <td><i class="far fa-smile"></i></td>
                                <td>Family</td>
                                <td>Yes</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 col-md-6 col-lg-4">
                <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi distinctio impedit mollitia aliquid
                    adipisci est eius at laborum consequuntur quam inventore, corrupti nesciunt id consequatur nisi
                    tenetur sunt exercitationem minus. </div>
            </div>

        <div class="row">
            <div class="col-sm-8 col-md-6 col-lg-4">
                <div> <button>afsdf</button></div>
            </div>
        </div>

    </div>
</div>

<?php require_once('Template/footer.phtml') ?>