<body>
<h2 style= text-align: center;>Admin User Panel Editing</h2>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">UserName</th>
      <th scope="col">CampsiteOwned</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
<?php $tableRowCount = 1; 
   foreach ($view->users as $users): ?>
    
  <tr>
    <th scope="row">'.$tableRowCount.'</th>
    <td>'.$users->getName().'</td>
    <td>Null</td>
    <td><a href="campsiteAdminUsers.php?id=<?php echo $users->getID()?>" class="btn btn-light">DELETE</a></td>
    <td><button>Delete</button></td>
  </tr>

  <?php $tableRowCount++; ?>
  
<?php endforeach; ?>
    
  </tbody>
</table>
</body>