<?php require_once 'Template/header.phtml'; ?>
<body>
<h2 style= text-align: center;>Admin User Panel Editing</h2>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Firstname</th>
      <th scope="col">Username</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
<?php $tableRowCount = 1; 
   foreach ($view->users as $user): ?>
    
  <tr>
    <th scope="row"><?php echo $tableRowCount ?></th>
    <td><?php echo $user->getFirstName() ?></td>
    <td><?php echo $user->getUserName() ?></td>
    <form action="<?php $_SERVER['PHP_SELF']?>" method="GET">
    <input type="hidden" name="userID" value="<?php echo $user->getUserID()?>">
    <td><button class="btn btn-light">DELETE</button></td>
    </form>
  </tr>

  <?php $tableRowCount++; ?>
  
<?php endforeach; ?>
    
  </tbody>
</table>
</body>

<?php require_once 'Template/footer.phtml'; ?>
