<?php require_once 'Template/header.phtml'; ?>
<?php 
$checkPagination = true; 
$checkPaginationForFavouriteLanding = false; 

// Doing this logic here, gives us more flexibility on what we can do. 

if($pagingCheck):

       $checkPaginationForFavouriteLanding = true; 
       if($pageNumber > 1)
       {
              $directNext = $pageNumber + 1;
              $directPrevius = $pageNumber - 1; 
       }

       else {
              $directPage= $pageNumber + 1;
              $checkPagination = false; 
       }

endif;
?>

<div class="container-fluid">
       <form class="form-filters" method="GET" action="<?php $_SERVER['PHP_SELF']?>">
              <div class="search-button">                       
                                   <input type="text" name="search-keyword" placeholder="Search from Campsite Name">
                                   <input type="hidden" name="search-action" value="searchBar">
                                   <button class="search-button-keyword" type="submit">Search</button><br><br>  
              </div>
       </form>
<div class="row">
       <div class="col-sm-3  media-filter-central">
              <form action="<?php $_SERVER['PHP_SELF']?>" method="GET">
                     <input type="hidden" name="search-action" value="searchFilter">
                     
                            <div class="form-group">
                                   <label for="exampleFormControlSelect2">
                                          <div class="alert alert-primary" role="alert">
                                                 Search From Filters
                                          </div>
                                   </label><br><br>
                                   <label for="form-control">
                                          <p>Filter from country </p>
                                   </label>
                                   <select multiple class="form-control" id="exampleFormControlSelect2" name="selectedCountry">
                                          <option value="France">France</option>
                                          <option value="Germany">Germany</option>
                                          <option value="Greece">Greece</option>
                                          <option value="Ireland">Ireland</option>
                                          <option value="Italy">Italy</option>
                                          <option value="Latvia">Latvia</option>
                                          <option value="Lithuania">Lithuania</option>
                                          <option value="Luxembourg">Luxembourg</option>
                                          <option value="Malta">Malta</option>
                                          <option value="Netherlands">Netherlands</option>
                                          <option value="Poland">Poland</option>
                                          <option value="Portugal">Portugal</option>
                                          <option value="Romania">Romania</option>
                                          <option value="Slovakia">Slovakia</option>
                                          <option value="Slovenia">Slovenia</option>
                                          <option value="Spain">Spain</option>
                                          <option value="Sweden">Sweden</option>
                                          <option value="United Kingdom">United Kingdom</option>
                                   </select>
                            </div><br>
                            
                            <div class="container-rating">
                                   <label for="rating">
                                          <p>Filter from ratings</p>
                                   </label>
                                   <div class="row">
                                          <span class="rating">
                                                 <input type="radio" class="rating-input" id="rating-input-1-5-5" name="rating-input-5" value="5">
                                                 <label for="rating-input-1-5-5" class="rating-star"></label>
                                                 <input type="radio" class="rating-input" id="rating-input-1-4-5" name="rating-input-5" value="4">
                                                 <label for="rating-input-1-4-5" class="rating-star"></label>
                                                 <input type="radio" class="rating-input" id="rating-input-1-3-5" name="rating-input-5" value="3">
                                                 <label for="rating-input-1-3-5" class="rating-star"></label>
                                                 <input type="radio" class="rating-input" id="rating-input-1-2-5" name="rating-input-5" value="2">
                                                 <label for="rating-input-1-2-5" class="rating-star"></label>
                                                 <input type="radio" class="rating-input" id="rating-input-1-1-5" name="rating-input-5" value="1">
                                                 <label for="rating-input-1-1-5" class="rating-star"></label>
                                          </span>
                                   </div>
                            </div><br>
                            <div class="container-facility">
                                   <label for="">
                                          <p>Filter from facility</p>
                                   </label>
                                   <div class="row">
                                          <div class="col-sm-8 col-md-6 col-lg-4">
                                                 <div>
                                                        <table>
                                                               <tr>
                                                                      <th colspan="2">Facility</th>
                                                               </tr>
                                                               <tr>
                                                                      <td><i class="fas fa-shower"></i></td>
                                                                      <td>shower</td>
                                                                      <td><input type="checkbox" name="shower" id="" value="1"></td>
                                                               </tr>
                                                               <tr>
                                                                      <td><i class="fas fa-wifi"></i></td>
                                                                      <td>wifi</td>
                                                                      <td><input type="checkbox" name="wifi" id="" value="1"></td>
                                                               </tr>
                                                               <tr>
                                                                      <td><i class="fas fa-coffee"></i></td>
                                                                      <td>Coffee</td>
                                                                      <td><input type="checkbox" name="coffe" id="" value="1"></td>
                                                               </tr>
                                                               <tr>
                                                                      <td><i class="fab fa-accessible-icon"></i></td>
                                                                      <td>Accessible</td>
                                                                      <td><input type="checkbox" name="disabe_facilties" value="1"
                                                                                    id=""></td>
                                                               </tr>
                                                               <tr>
                                                                      <td> <i class="fas fa-tint"></i></td>
                                                                      <td>Water</td>
                                                                      <td><input type="checkbox" name="water" id="" value="1"></td> 
                                                               </tr>
                                                               <tr>
                                                                      <td><i class="far fa-smile"></i></td>
                                                                      <td>Family</td>
                                                                      <td><input type="checkbox" name="family" id="" value="1"></td>
                                                               </tr>
                                                        </table>
                                                 </div>
                                          </div>
                                   
                            </div>
                            <div class="filter-button">
                                   <button id="filter-button">apply filter</button>
                            </div>
              </form>
       </div>
</div>


       <!-- Seciton for the searched campsite cards display-->
       <?php if($searchCheck): ?>
       <div class="col-9 media-card-central" style="float:right;">
              <?php  foreach ($view->campsite as $campsite): ?>
              <div class="row card-style" style="w
                                    height: 320px; margin-bottom:30px;">
                     <div class="card" id="campsite-card">
                            <div class="text-center">
                                   <div class="card-body">
                                          <div class="col-4" style="float:left;">
                                                 <img class="card-img-top" src=Images/<?php echo $campsite->getPhoto(); ?>
                                                   alt="Card image cap" id="campsite-image">
                                          </div>
                                          <div class="col-8" style="float:right;">
                                          <h5 class="card-title">
                                                 <?php echo $campsite->getCampsiteName(); 
                                                  $ID = $campsite->getCampsiteID(); ?>
                                          </h5>
                                           <div><?php echo $campsite->getCountry();?> </div>
                                           <div><?php $rating =  $campsiteData->getRatingAverage($ID); if($rating == 5)
                {
                    echo '<i class="fas fa-star" ></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>';
                }
                elseif($rating == 4){ echo '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>';}
                elseif($rating == 3){ echo '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>';}
                elseif($rating == 2){ echo '<i class="fas fa-star"></i><i class="fas fa-star"></i>';}
                elseif($rating == 1){
                    echo '<i class="fas fa-star"></i>';
                }?>
         </div>
                                               
                                                 <form action="<?php $_SERVER['PHP_SELF']; ?>" method="GET">
                                                        <?php  $ID = $campsite->getCampsiteID();
                                                              
                                                              if($userData->isUserLogged()):
                                                               if($campsiteData->checkCampIdInFavSes($ID)): ?>
                                                        <input type="submit" name="DisableFav" value="RemoveFav" class="btn btn-danger" style="height: 34px;">
                                                        <input type="hidden" name="favouriteCampsiteID" value=<?php
                                                               echo $campsite->getCampsiteID(); ?>>
                                                        <input type="hidden" name="pagination" value=<?php echo
                                                               $pageNumber ; ?>>
                                                        <input type="hidden" name="FavAction" value="remove">
                                                        <a href="campsitePage.php?campsiteID=<?php echo $campsite->getCampsiteID(); ?>"class="btn btn-secondary" style="height: 34px;">View</a>
                                                        <?php else: ?>
                                                        <input type="submit" name="AddFav" value="AddFav" class="btn btn-success" style="height: 34px;">
                                                        <input type="hidden" name="favouriteCampsiteID" value=<?php
                                                               echo $campsite->getCampsiteID(); ?>>
                                                        <input type="hidden" name="pagination" value=<?php echo
                                                               $pageNumber ; ?> >
                                                        <input type="hidden" name="FavAction" value="add">
                                                        <?php endif ?>
                                                        <?php endif ?>
                                                 </form>
                                          </div>
                                   </div>
                            </div>
                     </div>

              </div>
      
             
       <?php endforeach; ?>




       <?php endif ?>

       <!-- END Secton for the searched campsite cards display-->

       <!-- start Secton for the landing campsite cards display-->

       <?php if($landingCheck): ?>
       <div class="col-9 media-card-central" style="float:right;">
              <?php  foreach ($view->campsites as $campsite): ?>
              <div class="row card-style" style="
                                    height: 320px; margin-bottom:30px;">
                     <div class="card" id="campsite-card">
                            <div class="text-center">
                                   <div class="card-body">
                                          <div class="col-4" style="float:left;">
                                                 <img class="card-img-top" src=Images/<?php echo $campsite->getPhoto()
                                                 ; ?> alt="Card image cap" id="campsite-image">
                                          </div>
                                          <div class="col-8" style="float:right;">
                                          <h5 class="card-title">
                                                 <?php echo $campsite->getCampsiteName(); 
                                                  $ID = $campsite->getCampsiteID(); ?>
                                          </h5>
                                           <div><?php echo $campsite->getCountry();?> </div>
                                           <div><?php $rating =  $campsiteData->getRatingAverage($ID); if($rating == 5)
                {
                    echo '<i class="fas fa-star" ></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>';
                }
                elseif($rating == 4){ echo '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>';}
                elseif($rating == 3){ echo '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>';}
                elseif($rating == 2){ echo '<i class="fas fa-star"></i><i class="fas fa-star"></i>';}
                elseif($rating == 1){
                    echo '<i class="fas fa-star"></i>';
                }?>
         </div>
                                               
                                                 <form action="<?php $_SERVER['PHP_SELF']; ?>" method="GET">
                                                        <?php  $ID = $campsite->getCampsiteID();
                                                              
                                                              if($userData->isUserLogged()):
                                                               if($campsiteData->checkCampIdInFavSes($ID)): ?>
                                                        <input type="submit" name="DisableFav" value="RemoveFav" class="btn btn-danger" style="height: 34px;">
                                                        <input type="hidden" name="favouriteCampsiteID" value=<?php
                                                               echo $campsite->getCampsiteID(); ?>>
                                                        <input type="hidden" name="pagination" value=<?php echo
                                                               $pageNumber ; ?>>
                                                        <input type="hidden" name="FavAction" value="remove">
                                                        <a href="campsitePage.php?campsiteID=<?php echo $campsite->getCampsiteID(); ?>"class="btn btn-secondary" style="height: 34px;">View</a>
                                                        <?php else: ?>
                                                        <input type="submit" name="AddFav" value="AddFav" class="btn btn-success" style="height: 34px;">
                                                        <input type="hidden" name="favouriteCampsiteID" value=<?php
                                                               echo $campsite->getCampsiteID(); ?>>
                                                        <input type="hidden" name="pagination" value=<?php echo
                                                               $pageNumber ; ?>>
                                                        <input type="hidden" name="FavAction" value="add">
                                                        <?php endif ?>
                                                        <?php endif ?>
                                                 </form>
                                          </div>
                                   </div>
                            </div>
                     </div>

              </div>
      
       <?php endforeach; ?>
       </div>


       <?php endif ?>

       <!-- END Secton for the landing campsite cards display-->
       <?php if($pagingCheck): ?>

       <nav aria-label="Page navigation example" style="margin:auto;">
              <ul class="pagination justify-content-center">

                     <?php
                     

// Check if the boolean value is true then do something. 
if($checkPagination)
{
    
    
    
    echo '<li class="page-item"><a class="page-link" href="campsiteList.php?page='. $directPrevius .'">Previous</a></li>'; 
    echo '<li class="page-item"><a class="page-link" href="campsiteList.php?page='. $directNext .'">Next</a></li>';
}

else 
{

    echo '<li class="page-item"><a class="page-link" href="campsiteList.php?page='.$directPage.'">Next</a></li>';
}

// for ($i=1; $i < $nOfPages; $i++)
//  { 

//     echo '<li class="page-item"><a class="page-link" href="campsiteList.php?page='.$i.'"></a></li>';
// }

       
?>
              </ul>
       </nav>
       <?php endif; ?>
</div>
       <?php require_once 'Template/footer.phtml';?>
</div>