<?php require_once 'Template/header.phtml'; ?>
<body>
<?php 
$checkPagination = true; 

// Doing this logic here, gives us more flexibility on what we can do. 

       if($pageNumber > 1)
       {
              $directNext = $pageNumber + 1;
              $directPrevius = $pageNumber - 1; 
       }

       else {
              $directPage= $pageNumber + 1;
              $checkPagination = false; 
       }
?>
<h2 style= text-align: center;>Admin Campsite Panel Editing</h2>
       <div class="container">
              <div class="card-search">
                     <div class="row">
                            <?php  foreach ($view->campsites as $campsite):?>
                            <div class="col-sm-3 col-md-3 col-lg-3">
                                   <div class="card" id="campsite-card">
                                          <div class="text-center">
                                                 <div class="card-body">
                                                        <h5 class="card-title">
                                                               <?php echo $campsite->getCampsiteName();  ?>
                                                        </h5>
                                                        <img class="card-img-top" src=Images/<?php echo $campsite->getPhoto()
                                                        ; ?> alt="Card image cap" id="campsite-image">
                                                        <p class="card-text" id="address-card">card address here</p><br>
                                                        <form action="<?php $_SERVER['PHP_SELF']; ?>" method="GET">
                                                               <?php  $ID = $campsite->getCampsiteID(); 
                                                                // var_dump($ID);
                                                                 //die()                                     
                                                                ?>
                                                               <input type="submit" name="" value="Remove"
                                                                      class="btn btn-danger">
                                                               <input type="hidden" name="campsiteID" value=<?php
                                                                      echo $campsite->getCampsiteID(); ?>>
                                                               <input type="hidden" name="pageNumber" value=<?php echo
                                                                      $pageNumber ; ?>>
                                                               <input type="hidden" name="AdminAction" value="remove">
                                                               
                                                        </form>
                                                 </div>
                                          </div>
                                   </div>

                            </div>
                                   <?php endforeach; ?>

                     </div>
                     
              </div>

       </div>


       <nav aria-label="Page navigation example" style="margin:auto;">
              <ul class="pagination justify-content-center">

<?php
                     

// Check if the boolean value is true then do something. 
if($checkPagination)
{
    
    
    
    echo '<li class="page-item"><a class="page-link" href="campsiteAdmin.php?campsitePage=campsitePage&pageNumber='. $directPrevius .'">Previous</a></li>'; 
    echo '<li class="page-item"><a class="page-link" href="campsiteAdmin.php?campsitePage=campsitePage&pageNumber='. $directNext .'">Next</a></li>';
}

else 
{

    echo '<li class="page-item"><a class="page-link" href="campsiteAdmin.php?campsitePage=campsitePage&pageNumber='.$directPage.'">Next</a></li>';
}
 ?>

</ul>
       </nav>

<?php require_once 'Template/footer.phtml'; ?>