<?php require_once('Template/header.phtml') ?>

<!--Image slider-->

<div id="my-slider" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="Images/slides/slider1.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="Images/slides/slider2.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="Images/slides/slider3.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#my-slider" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#my-slider" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    <div class="carousel-caption">
        <input type="text" placeholder=" Where do you want to go ?" id="textarea-carosel" >    
        <button class="" id="search-bar-carousel">Search</button>
    </div>
</div>
    
<!--Print some campsites-->
<div class="container">
    <div class="row">
  <?php  foreach ($view->campsites as $campsite) {
    echo '
    <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="card">
                    <img class="card-img-top" src="Images/Default.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">' . $campsite->getCampsiteName() .  '</h5>
                        <p class="card-text">This is a wider card with supporting text</p>
                        <a href="#" class="btn btn-primary">See more</a>
                        <a href="#"> <i class="material-icons" style="font-size:36px">favorite_border</i></a> 
                    </div>
                </div>
     </div>'; 
                        }?>
    </div>
</div>

</body>

<?php require_once('Template/footer.phtml') ?>