<?php require_once('Template/header.phtml') ?>
<?php unset($_SESSION['campsitedID']); ?>

<!--Image slider-->

<div id="my-slider" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="Images/slides/slider1.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="Images/slides/slider2.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="Images/slides/slider3.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#my-slider" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#my-slider" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
    
<!--Print some campsites-->
<div class="container">
    <div class="row">
  <?php  foreach ($view->campsites as $campsite): ?>
    
    <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="card">
                    <img class="card-img-top" src="Images/Default.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title"><?php  echo $campsite->getCampsiteName(); ?> </h5>
                        <p class="card-text">This is a wider card with supporting text</p>
                        <a href="campsitePage.php?hshid=<?php $_SESSION['campsiteID'][] = $campsite->getCampsiteID(); $campsiteID =  $campsite->getCampsiteID(); $hash = password_hash($campsiteID, PASSWORD_DEFAULT); $_SESSION['hshid'] = $hash; echo $hash; ?>" class="btn btn-primary">See more</a>
                    </div>
                </div>
                
    </div> 

    <?php  endforeach ?>
                 
    </div>
    
</div>

</body>

<?php require_once('Template/footer.phtml') ?>