
<?php require_once('Template/header.phtml') ?>

<title>Login page</title>
<body>

<div id="login-title"> 
    <h1>Register Here</h1>
</div>
<!--
    you can substitue the span of reauth email for a input with the email and
    include the remember me checkbox
    -->
    <div class="container">
        <div class="card card-container">
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
            <p id="profile-name" class="profile-name-card"></p>
            <form class="form-signin" action= "<?php $_SERVER['PHP_SELF']?>" method= 'post'>
            <span id="reauth-email" class="reauth-email"></span>
                <input type="text" id="inputFirstName" class="form-control" placeholder="First Name" name="firstname" required autofocus>
                <input type="text" id="inputLastName" class="form-control" placeholder="Last Name" name="lastname" required>
                <input type="email" id="inputEmail" class="form-control" placeholder="Email address" name="uname" required>
                <input type="password" id="inputPassword" class="form-control" placeholder="Password" name= "upassword" required>
                <input type="password" id="inputPassword" class="form-control" placeholder="Confirm Password" name= "confirmedpassword" required>
                <div id="remember" class="checkbox">
                    <label>
                        <input type="checkbox" value="remember-me"> Remember me
                    </label>
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit" name="submit_signin">Register</button>
            </form><!-- /form -->
        </div><!-- /card-container -->
    </div><!-- /container -->
    
    <?php require_once('Template/footer.phtml') ?>

