<?php 

require_once 'Template/header.phtml';

?>
<body>
    <section>
        <div class="container" id="user_section">
        <div class="col-sm-4 col-md-4 col-lg-4">
            <div class="row">
            <div class="user_profile">
                    <img class="circleImg" src="Images/avatar.png" alt="Avatar">
                    <p class="userName_profile"> Hello</p>
            </div>
            </div>
            <div class="row">
            <table class ="table-user">
                <tr><th>First Name</th>
                <td>Mark</td></tr>
                <tr><th>Last Name</th>
                <td>Karim</td></tr> 
                <tr><th>User Name</th>
                <td>Karim</td></tr> 
            </table><br>
        </div>
        </div>
        <button>Reset your password</button>
        <button>Change your details</button>
        </div>
       
    </section>

<?php require_once 'Template/footer.phtml';

    